import { useState, useCallback, useEffect } from 'react';
import { CartItem, MenuItem, PendingOrder, Order } from '../types';
import { orderApi } from '../services/api';

// Local storage key for pending orders (as backup/fallback)
const PENDING_ORDERS_KEY = 'niyabalawa_pending_orders';

export const useBilling = () => {
  const [cart, setCart] = useState<CartItem[]>([]);
  const [tokenNumber, setTokenNumber] = useState<string>('');
  const [orderType, setOrderType] = useState<'dine-in' | 'take-away'>('dine-in');
  const [pendingOrders, setPendingOrders] = useState<PendingOrder[]>([]);

  // Load pending orders from backend on mount
  useEffect(() => {
    const loadPendingOrders = async () => {
      try {
        const orders = await orderApi.getPendingOrders();
        setPendingOrders(orders.map((order: PendingOrder) => ({
          ...order,
          createdAt: new Date(order.createdAt),
          timestamp: new Date(order.createdAt)
        })));
      } catch (error) {
        console.error('Error loading pending orders from backend:', error);
        // Fallback to localStorage if backend fails
        const stored = localStorage.getItem(PENDING_ORDERS_KEY);
        if (stored) {
          try {
            const parsed = JSON.parse(stored);
            setPendingOrders(parsed.map((order: PendingOrder) => ({
              ...order,
              createdAt: new Date(order.createdAt || order.timestamp),
              timestamp: new Date(order.timestamp || order.createdAt)
            })));
          } catch (parseError) {
            console.error('Error parsing stored orders:', parseError);
          }
        }
      }
    };

    loadPendingOrders();
  }, []);

  // Save pending orders to localStorage as backup whenever they change
  useEffect(() => {
    localStorage.setItem(PENDING_ORDERS_KEY, JSON.stringify(pendingOrders));
  }, [pendingOrders]);

  const addToCart = useCallback((item: MenuItem, portion?: 'half' | 'full') => {
    // Determine price based on item type
    let price: number;
    
    if (portion === 'half') {
      price = Number(item.halfPrice) || 0;
    } else if (portion === 'full') {
      price = Number(item.fullPrice) || 0;
    } else {
      // For addons, desserts, drinks - use single price field
      // Fallback to halfPrice for old items that were created with half_price/full_price format
      // Convert to number in case backend sends as string
      price = Number(item.price) || Number(item.halfPrice) || Number(item.fullPrice) || 0;
    }
    
    const cartItemId = `${item.id}-${portion || 'default'}`;
    
    setCart(prevCart => {
      const existingItem = prevCart.find(cartItem => cartItem.id === cartItemId);
      
      if (existingItem) {
        return prevCart.map(cartItem =>
          cartItem.id === cartItemId
            ? { ...cartItem, quantity: cartItem.quantity + 1 }
            : cartItem
        );
      } else {
        return [...prevCart, {
          id: cartItemId,
          name: item.name,
          price,
          quantity: 1,
          portion,
          category: item.category,
          kitchen: item.kitchen, // Include kitchen property for printing
          // Set default rice type for main dishes (set menu)
          riceType: item.category === 'main' ? 'White Rice' : undefined,
          ricePrice: 0
        }];
      }
    });
  }, []);

  const changeRiceType = useCallback((cartItemId: string, riceName: string, ricePrice: number) => {
    setCart(prevCart =>
      prevCart.map(item =>
        item.id === cartItemId && item.category === 'main'
          ? { 
              ...item, 
              riceType: riceName,
              ricePrice: ricePrice
            }
          : item
      )
    );
  }, []);

  const removeFromCart = useCallback((id: string) => {
    setCart(prevCart => prevCart.filter(item => item.id !== id));
  }, []);

  const clearCart = useCallback(() => {
    setCart([]);
    setTokenNumber('');
  }, []);

  const updateQuantity = useCallback((id: string, quantity: number) => {
    if (quantity <= 0) {
      setCart(prevCart => prevCart.filter(item => item.id !== id));
      return;
    }
    
    setCart(prevCart =>
      prevCart.map(item =>
        item.id === id ? { ...item, quantity } : item
      )
    );
  }, []);

  const savePendingOrder = useCallback(async () => {
    if (cart.length === 0) return null;

    try {
      const totalAmount = cart.reduce((sum, item) => sum + ((item.price + (item.ricePrice || 0)) * item.quantity), 0);
      
      const orderData = {
        items: cart,
        total: totalAmount,
        tokenNumber: '', // Will be generated by backend
        timestamp: new Date(),
        orderType,
        status: 'pending' as const
      };

      const response = await orderApi.createOrder(orderData);
      const order = response; // Backend returns order directly

      const pendingOrder: PendingOrder = {
        ...order,
        timestamp: new Date(order.createdAt),
        status: 'pending'
      };

      setPendingOrders(prev => [...prev, pendingOrder]);
      setTokenNumber(order.tokenNumber);
      clearCart();
      return pendingOrder;
    } catch (error) {
      console.error('Error saving pending order to backend:', error);
      // Fallback to local save - use simple sequential number
      const localToken = (Date.now() % 10000).toString(); // Simple number from timestamp
      const now = new Date();
      const order: PendingOrder = {
        items: [...cart],
        total: cart.reduce((sum, item) => sum + ((item.price + (item.ricePrice || 0)) * item.quantity), 0),
        tokenNumber: localToken,
        timestamp: now,
        createdAt: now,
        orderType,
        status: 'pending'
      };

      setPendingOrders(prev => [...prev, order]);
      setTokenNumber(localToken);
      clearCart();
      return order;
    }
  }, [cart, orderType, clearCart]);

  const loadPendingOrder = useCallback((token: string) => {
    const order = pendingOrders.find(o => o.tokenNumber === token);
    if (order) {
      setCart([...order.items]);
      setTokenNumber(order.tokenNumber);
      setOrderType(order.orderType);
      return order;
    }
    return null;
  }, [pendingOrders]);

  const loadOrderForEdit = useCallback((order: Order | PendingOrder) => {
    // Load any order (pending or paid) into cart for editing
    setCart([...order.items]);
    setTokenNumber(order.tokenNumber);
    setOrderType(order.orderType);
  }, []);

  const updatePendingOrder = useCallback(async (token: string) => {
    try {
      const totalAmount = cart.reduce((sum, item) => sum + ((item.price + (item.ricePrice || 0)) * item.quantity), 0);
      const orderData = {
        items: cart,
        total: totalAmount
      };
      
      await orderApi.updateOrder(token, orderData);
      
      setPendingOrders(prev => 
        prev.map(order => 
          order.tokenNumber === token 
            ? {
                ...order,
                items: [...cart],
                total: totalAmount
              }
            : order
        )
      );
      
      // Clear cart and reset token after updating
      clearCart();
    } catch (error) {
      console.error('Error updating order on backend:', error);
      // Fallback to local update
      setPendingOrders(prev => 
        prev.map(order => 
          order.tokenNumber === token 
            ? {
                ...order,
                items: [...cart],
                total: cart.reduce((sum, item) => sum + ((item.price + (item.ricePrice || 0)) * item.quantity), 0)
              }
            : order
        )
      );
      
      // Clear cart and reset token after updating
      clearCart();
    }
  }, [cart, clearCart]);

  const completePendingOrder = useCallback(async (token: string) => {
    try {
      await orderApi.completeOrder(token);
      setPendingOrders(prev => prev.filter(order => order.tokenNumber !== token));
      clearCart();
    } catch (error) {
      console.error('Error completing order on backend:', error);
      // Fallback to local completion
      setPendingOrders(prev => prev.filter(order => order.tokenNumber !== token));
      clearCart();
    }
  }, [clearCart]);

  const deletePendingOrder = useCallback(async (token: string) => {
    try {
      await orderApi.deleteOrder(token);
      setPendingOrders(prev => prev.filter(order => order.tokenNumber !== token));
      console.log(`✅ Deleted order ${token}`);
    } catch (error) {
      console.error('Error deleting order on backend:', error);
      // Fallback to local deletion
      setPendingOrders(prev => prev.filter(order => order.tokenNumber !== token));
    }
  }, []);

  const deleteAllOrders = useCallback(async () => {
    try {
      const result = await orderApi.deleteAllOrders();
      setPendingOrders([]);
      console.log(`✅ Deleted ${result.deletedCount} orders`);
      return result.deletedCount;
    } catch (error) {
      console.error('Error deleting all orders on backend:', error);
      // Fallback to local deletion
      setPendingOrders([]);
      return 0;
    }
  }, []);

  const total = cart.reduce((sum, item) => {
    const itemTotal = item.price * item.quantity;
    const riceTotal = (item.ricePrice || 0) * item.quantity;
    return sum + itemTotal + riceTotal;
  }, 0);

  return {
    cart,
    tokenNumber,
    total,
    orderType,
    pendingOrders,
    addToCart,
    updateQuantity,
    removeFromCart,
    clearCart,
    setOrderType,
    changeRiceType,
    savePendingOrder,
    loadPendingOrder,
    loadOrderForEdit,
    updatePendingOrder,
    completePendingOrder,
    deletePendingOrder,
    deleteAllOrders
  };
};